timezone: America/New_York
# source: source_folder
collections:
  posts:
    output:   true
remote_theme: BlackrockDigital/startbootstrap-stylish-portfolio
repository: things-nyc/things-nyc.github.io
permalink: pretty
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"